// MIT License
// 
// Copyright (c) 2025 Polina "Aura" N.
// Copyright (c) 2025 Julia Nechaevskaya
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.


#include "loto-keno.h"


//
// Title screen
//

const char *lang_title_name;
const char *lang_title_version;
const char *lang_title_developed_by;
const char *lang_title_authors;
const char *lang_title_key_f1;
const char *lang_title_key_f2;
const char *lang_title_press_any_key;

const char **lang_title_quote;
int lang_title_quote_size;

static const char *txt_title_quotes_eng[] = {
    "Chance of Samurai? 1 in 10. Try now!",
    "Blub-blub-blub... A-OOO-OOO-Oo!?",
    "Gambling isn’t a game, it’s life!",
    "Hope for luck, but bet smart!",
    "Every round — your chance to win!",
    "HNA!™ Samurai Approved.",
    "Lost? Try again!",
    "CGA: 4 colors, 1 winner.",
    "Luck is an illusion. Or is it?",
    "Bet like a samurai, lose like a poet.",
    "The gods of luck are watching.",
    "Press any key... if you dare.",
    "Your fate is just a number away.",
    "More colors? No. More luck? Also no.",
    "One bet to rule them all.",
    "Winners smile. Destiny smirks.",
    "It’s not gambling. It’s art.",
    "Today’s luck: Undefined.",
    "The samurai whispers... 'Again.'",
    "Numbers don’t lie. Or do they?",
    "Pick wisely. Or don’t. Who cares?",
    "Fortune favors... probably not you.",
    "The CGA colors are watching you.",
    "Feeling lucky? I wouldn’t be.",
    "Only 4 colors. Only 2 choices.",
    "Who needs 256 colors anyway?",
    "Win = skill. Lose = pure chance.",
    "Do you believe in fate? Good luck!",
    "The bet chooses you, not vice versa.",
    "Just one more round. Just one more...",
    "This is a game about trust issues.",
    "90% luck, 10% regret.",
    "Blub-blub-blub... fate awaits!",
    "The pixels demand sacrifice.",
    "HNA!™— The Ultimate Truth.",
    "CGA. Where dreams go to die.",
    "Hope is just a lucky guess.",
    "You blinked. Luck noticed.",
    "Win? Lose? The answer is: Yes.",
    "Fate is four colors deep.",
    "One click. One fate.",
    "Luck never sleeps.",
    "Nothing personal. Just numbers.",
    "CGA pixels whisper secrets.",
    "Trust the process. Or don’t.",
    "Your luck was here. Now it’s gone.",
    "50% hope. 50% regret.",
    "Is it skill? Or just luck again?",
    "Bet small. Dream big. Lose anyway.",
    "Winning is temporary. Luck is forever.",
};

static const char *txt_title_quotes_rus[] = {
    "Шанс на самурая? 1 к 10. Проверь удачу!",
    "Будь-будь-будь... А-ОООО-ООО-Оо!?",
    "Азарт — это не игра, а стиль жизни!",
    "Надейся на удачу, но ставь с умом!",
    "Каждый раунд — шанс стать чемпионом!",
    "ХНА!™ Одобрено самураями.",
    "Если ты проиграл — попробуй ещё раз!",
    "CGA. 4 цвета. 1 победитель.",
    "Удача — иллюзия. Или нет?",
    "Ставь как самурай, проигрывай как поэт.",
    "Боги удачи пристально следят.",
    "Нажмите клавишу... если не боитесь.",
    "Ваша судьба — это просто число.",
    "Больше цветов? Нет. Больше шансов? Нет.",
    "Одна ставка, чтобы править всем.",
    "Победители улыбаются. Судьба смеётся.",
    "Это не игра. Это искусство провала.",
    "Сегодняшняя удача: неопределённа.",
    "Самурай шепчет... 'Ставь ещё'.",
    "Числа не врут. Или всё-таки врут?",
    "Выберите мудро. Или нет. Всё равно.",
    "Фортуна благоволит... кому-то.",
    "Эти 4 цвета следят за вами.",
    "Чувствуете удачу? Напрасно.",
    "Всего 4 цвета. Всего 2 выбора.",
    "Кому нужны 256 цветов?",
    "Победа — навык. Поражение — случай.",
    "Верите в судьбу? Тогда вам не повезёт.",
    "Ставка выбирает вас, а не наоборот.",
    "Только один раунд. Только один...",
    "Это игра о доверии. Которого нет.",
    "90% удачи, 10% сожаления.",
    "Будь-будь-будь... Судьба зовёт!",
    "Эти пиксели требуют жертв.",
    "ХНА!™ — Истина вне доказательств.",
    "CGA. Где мечты умирают 50/50.",
    "Надежда — просто удачная догадка.",
    "Моргнули? Удача это заметила.",
    "Выигрыш? Проигрыш? Ответ: Да.",
    "Судьба прячется в 4 цветах.",
    "Один клик — одна судьба.",
    "Удача не спит, а ждёт.",
    "Ничего личного. Только цифры.",
    "Пиксели CGA знают тайны.",
    "Доверьтесь судьбе. Или не стоит.",
    "Удача была тут. Теперь её нет.",
    "50% надежды. 50% сожаления.",
    "Это навык? Или просто везение?",
    "Ставьте мало. Мечтайте о многом.",
    "Выигрыш временный. Удача вечна.",
};

//
// Help
//

const char **lang_help_lines;
int lang_help_lines_count;

static const char *txt_help_lines_eng[] = {
    "┌────────────────────────────────────┐",
    "│          LOTO KENO - RULES         │",
    "├────────────────────────────────────┤",
    "│ You start with 10 points.          │",
    "│ You can bet from 1 up to your      │",
    "│ current amount.                    │",
    "│ Then make a choice and see         │",
    "│ if luck is on your side.           │",
    "│                                    │",
    "│ If HNA! appears, win or loss       │",
    "│ is doubled. Game continues until   │",
    "│ you run out of points.             │",
    "│                                    │",
    "│ If they reach zero, you lose.      │",
    "│                                    │",
    "│ Controls:                          │",
    "│ ← and → - select                   │",
    "│ ↑ and ↓ - change bet               │",
    "│ ENTER   - confirm                  │",
    "│ ALT + ENTER - full screen mode     │",
    "│                                    │",
    "│            Good luck!              │",
    "└────────────────────────────────────┘",
};

static const char *txt_help_lines_rus[] = {
    "┌────────────────────────────────────┐",
    "│          ЛОТО КЕНО - ПРАВИЛА       │",
    "├────────────────────────────────────┤",
    "│ В начале у вас есть 10 очков.      │",
    "│ Вы можете сделать ставку от 1      │",
    "│ до вашего текущего количества.     │",
    "│ Затем выберите вариант и узнайте,  │",
    "│ повезло ли вам.                    │",
    "│                                    │",
    "│ Если появляется ХНА!, выигрыш      │",
    "│ или проигрыш удваивается. Игра     │",
    "│ продолжается, пока у вас есть      │",
    "│ очки. Если они закончатся, вы      │",
    "│ проиграете.                        │",
    "│                                    │",
    "│ Управление:                        │",
    "│ ← и → - выбор                      │",
    "│ ↑ и ↓ - ставки                     │",
    "│ ENTER - подтвердить                │",
    "│ ALT + ENTER - полноэкранный режим  │",
    "│                                    │",
    "│               Удачи!               │",
    "└────────────────────────────────────┘",
};

//
// Game field
//

const char *lang_game_score;
const char *lang_game_bet;
const char *lang_game_round;
const char *lang_game_bud_bud_bud;
const char *lang_game_aaa_ooo_ooo;
const char *lang_game_hna;

int resultQuoteIndex = -1;
int resultIsWin = 0; // 1 — выигрыш, 0 — проигрыш

const char **lang_game_win_quote;
const char **lang_game_loose_quote;
int lang_game_quote_win_size;
int lang_game_quote_loose_size;

static const char *txt_game_win_quotes_eng[] = {
    // [PN] Победные фразы:
    "Thank you!",
    "Very filling!",
    "YES! Good!",
    "Your call is very important to us!",
    "You got the job!",
    "Hooray! The milk didn't boil over!",
    "Now you are a senior samurai!",
    "A limousine is on its way for you.",
    "You found the meaning of life!",
    "Well, now you are a robot!",
    "I allow you to eat another cookie!",
    "You are twice as powerful now!",
    "Cats approve your choice.",
    "The barbecue is already sizzling!",
    "Magnificent, 10 out of 10!",
    "Wow! Oh! Ah! Unbelievable!",
    "You gave me hope!",
    "Your legs are beautiful!",
    "YES! THANK YOU!",
    "Now you can drink tea.",
    "Approved by kangaroos!",
    "You are perfect!",
    "Well, that’s wonderful!",
    "Fair enough!",
    "Excellent! Poisonous!",
    "The banana approves your win!",
    "A cat nodded in respect.",
    "The neighbor claps through the wall!",
    "The bike rolled up by itself!",
    "The universe raised an eyebrow.",
    "Even a robot said, \"Wow.\"",
    "Luck just gave you a thumbs up!",
    "A potato has praised you.",
    "Somewhere, a math nerd weeps.",
    "This win is dog-certified!",
    "Hooray! Time for some tea.",
    "A crow yelled, \"Victory!\"",
    "Aliens are now interested.",
    "Someone just cheered outside.",
    "The chair creaked happily.",
    "A professor is baffled.",
    "A chick is proud of you.",
    "Your bet just saved a penguin!",
    "Destiny whispers, \"Take it!\"",
    "You cracked the luck code!",
    "Broccoli declared you a hero.",
    "The universe winked at you.",
    "Gravity nodded in approval.",
    "You just won an invisible prize!",
    "You are a bet-shaman!",
    "Someone sighed in relief.",
    "Even the kettle is proud!",
    "A samurai approved this.",
    "Words appeared on the wall.",
    "The lamp blinked with joy.",
    "Destiny just sent you a sign.",
    "A rainbow just got brighter.",
    "Even mosquitoes respect you!",
    "Your fridge is now happier.",
    "Someone just jumped in joy!",
    "This is real – you won!",
    "You got a message: \"Nice!\"",
    "A goose gave you a nod.",
    "The calendar says \"LUCKY.\"",
    "Even the internet worked!",
    "Dumplings now respect you.",
    "The clock blinked twice – a sign!",
    "You unlocked life’s secret!",
    "Somewhere, victory music plays.",
    "Someone mentally applauded.",
    "A tree leaned closer to you.",
    "You're known in the luck club!",
    "Someone screamed, \"WHAT A WIN!\"",
    "The clouds accepted your bet.",
    "You are now a luck master.",
    "Even a fish is impressed!",
    "Your win is now in history.",
    "Satellites recorded this.",
    "A chicken just winked at you.",
    "The door opened by itself.",
    "The clock hit 7:77 – a sign!",
    "You’re now in the chronicles.",
    "The ice clinked in approval.",
    "A statistician just sighed.",
    "Your shadow nodded at you.",
    "An unseen goal was scored.",
    "The table’s corner got softer.",
    "A cookie cracked in victory.",
    "Champagne popped somewhere.",
    "Your alarm became nicer.",
    "A parade started outside.",
    "Your shoes are now fancier.",
    "The rain missed only you.",
    "The pencil sharpened itself!",
    "A token flipped somewhere.",
    "You are walking triumph!",
    "Your bet made the textbooks.",
    "A tram just cheered for you.",
    "Someone passed an exam.",
    "An elevator button pressed itself.",
    "Even ants are celebrating.",
    "Your name means \"lucky\" now!",
    "A record spot just opened.",
    "Your phone charged +1% free!",
    "Your hair fell perfectly!",
    "Right now, an exam was passed.",
    "A vault creaked open a little.",
    "A spoon didn’t fall in soup!",
    "Even pillows feel comfier.",
    "The power button lit up first.",
    "Someone just believed in luck.",
    "Your wallet grew a bit.",
    "Someone just found $20.",
    "A free coffee awaits you!",
    "Local cats now respect you.",
    "Your slippers are in place!",
    "A book opened to the right page.",
    "Tea boiled faster just for you.",
    "A lightbulb glowed brighter.",
    "A luck portal just opened.",
    "Someone hit \"All in\" by mistake.",
    "A grandma just nodded at you.",
    "You’re an official luck master!",
    "Destiny sent you applause.",
    "The screen now says \"YOU ROCK!\"",
    // [JN] Let’s add some nonsense!
    "Tumba-pumba!",
    "Menno-zamenno.",
    "Pooo-o-o-o!",
    "Tsa-ah!",
    "Oozyoo!",
    "E-eh!",
    "O-oh!",
    "Decent.",
    "Proper.",
    "D!",
    "Byr-byr-byr!",
    "Dzaytsa!!",
    "Lord, have mercy!",
    "Coins are jingling!",
    "Acha-acha!",
    "Aaah-eeee!",
    "Pickles!",
    "Tomatoes!",
    "Bonus on loyalty card!",
    "Just like Friday!",
    "Come again!",
    "Must-do, must-do!",
    "Hhhkkk!",
    "Ra-ta-ta-ta!",
    "Aa, ooo-oo-oo!",
    // [ND]
    "Rottsyu!",
    "M'daoh!",
    "D'yass!",
    "Gkoonya!",
    "Zao-zhunn!",
};

static const char *txt_game_loose_quotes_eng[] = {
    "Pancakes got burned.",
    "Well, almost!",
    "The cat is disappointed in you.",
    "Just a little short!",
    "You are still beautiful!",
    "The rabbit is disappointed.",
    "Your CPU overheated.",
    "Your glasses fell off.",
    "The neighbor looked at you sadly.",
    "Oops! Op-op!",
    "That was unthinkable!",
    "You are my hero! But no.",
    "Sad trombone sound.",
    "You were tricked!",
    "Almost! (but no).",
    "The carpet is dissatisfied.",
    "Someone sighed in the corner.",
    "The pancake ran away.",
    "It was an experiment!",
    "Everything went off course!",
    "The bicycle silently rode away.",
    "Now try again!",
    "The chicken said 'no'.",
    "System failure.",
    "Banana canceled!",
    "The kettle sighed in disappointment.",
    "The cat walked into another room.",
    "Fate pretended it wasn’t there.",
    "Someone whispered, \"Oh, unlucky!\"",
    "The keyboard sighed with you.",
    "A fork slid off the table.",
    "The lightbulb flickered sadly.",
    "The chair creaked disapprovingly.",
    "A dumpling sank in the pot.",
    "The TV switched to commercials.",
    "The radio played a sad song.",
    "The book closed by itself.",
    "The calendar showed Monday.",
    "The sugar didn’t dissolve.",
    "A fortune note fell out.",
    "Glasses slipped off your nose.",
    "The pen stopped writing.",
    "A meatball burned on the pan.",
    "The elevator left without you.",
    "Someone shut the window.",
    "The wheel of fate popped.",
    "A frog croaked in sympathy.",
    "Somewhere, a goose wept.",
    "Fate sent you a meme.",
    "The wind took your hope.",
    "The spoon fell into the soup.",
    "A robot sighed somewhere.",
    "The clock ran five minutes slow.",
    "A cloud moved the wrong way.",
    "Your shoes got a bit tighter.",
    "Your shoelaces untied.",
    "The elevator button broke.",
    "The coin landed on its edge.",
    "The pen ran out of ink.",
    "The cat lazily turned away.",
    "The door creaked suspiciously.",
    "The candle flickered.",
    "A weird draft passed by.",
    "A fork hit the floor.",
    "The chicken said, \"No.\"",
    "The remote’s batteries died.",
    "Your browser tab closed itself.",
    "The mouse froze for a second.",
    "The power flickered.",
    "A sudden storm began.",
    "The book opened to a sad page.",
    "Your headphones tangled up.",
    "Your coffee got cold too fast.",
    "The keyboard swallowed a key.",
    "The TV remote disappeared.",
    "The phone died at the worst time.",
    "A wallpaper corner peeled off.",
    "A chocolate piece fell.",
    "Google gave the wrong answer.",
    "A stranger knocked on the door.",
    "The lightbulb burned out.",
    "A sticky note went missing.",
    "The umbrella broke in the rain.",
    "A hole appeared in your pocket.",
    "The window shut itself.",
    "The tea was too strong.",
    "The sock pair didn’t match.",
    "The staircase got longer.",
    "The chair wobbled suddenly.",
    "Coffee spilled on the paper.",
    "Someone coughed judgmentally.",
    "The subway doors shut too soon.",
    "The chicken said \"No\" again.",
    "The calendar date changed suddenly.",
    "Your ear itched at the worst time.",
    "Your foot got tangled in the blanket.",
    "The oven refused to heat up.",
    "Somewhere, a chest snapped shut.",
    "The escalator button did nothing.",
    "The fireplace went out suddenly.",
    "The grass stayed brown.",
    "A memory card vanished.",
    "The monitor turned gray.",
    "The kettle boiled too soon.",
    "The curtain moved on its own.",
    "A cloud blocked the sun.",
    "The jacket had no hood.",
    "A paper flew off the table.",
    "A bridge turned drawbridge.",
    "Someone sneezed in another room.",
    "A shop door closed in your face.",
    "The trolley window fogged up.",
    "The lightbulb flickered twice.",
    "The water bottle got too warm.",
    "A raindrop hit your forehead.",
    "Your ear tickled unexpectedly.",
    "The fork was slightly bent.",
    "The clock ticked louder.",
    "A paper plane crashed.",
    "A lighter flame went out.",
    "The batteries were the wrong size.",
    "A program closed without saving.",
    "A jar refused to open.",
    "The marshmallow sank in cocoa.",
    "The coin landed the wrong way.",
    // [JN] Let’s add more nonsense!
    "Don’t do it!",
    "Don’t need anything.",
    "Peeeeh!",
    "Nope.",
    "Nah.",
    "Extravagance!",
    "PEEEEeeeh!",
    "Bad purchase.",
    "Not enoughness.",
    "Ptsyuk!",
    "Goodbye then.",
    "Come again!",
    "Nobody said!",
    "TRRRrrsh!",
    "Pso!",
    "Ktslo-o!",
    "Pzleh-eh!",
    "Pyyyyy!",
    "Bankruptcy!",
    "Roof’s gone, water’s dripping.",
    "Unsatisfactory.",
    "POO-OOP!",
    "P-f-f-f-f...",
    "Cap fell sideways.",
    "Horse theft!",
    // [ND]
    "Trysh.",
    "Zhzhytz.",
    "Syomsh.",
    "Luffrr.",
    "Mryaks.",
};

static const char *txt_game_win_quotes_rus[] = {
    // [PN] Победные фразы:
    "Спасибо!",
    "Очень сытно!",
    "ДА! Хорошо!",
    "Ваш звонок очень важен для нас!",
    "Вы приняты на работу!",
    "Ура! Молоко не убежало!",
    "Теперь вы старший самурай!",
    "За вами выехал лимузин.",
    "Вы нашли смысл жизни!",
    "Ну вот, теперь вы робот!",
    "Разрешаю съесть ещё печенье!",
    "Вы в два раза мощнее!",
    "Коты одобряют ваш выбор.",
    "Шашлыки уже жарятся!",
    "Великолепно, 10 из 10!",
    "Вау! О! А! Ничего себе!",
    "Вы дали мне надежду!",
    "Ваши ноги прекрасны!",
    "ДАА! СПАСИБО!",
    "Теперь можно пить чай.",
    "Одобрено кенгуру!",
    "Вы идеальны!",
    "Что ж, замечательно!",
    "Справедливо!",
    "Превосходно! Ядовито!",
    "Банан одобряет ваш успех!",
    "Кот уважительно кивнул.",
    "Сосед хлопает вам из-за стены!",
    "Велосипед подъехал к вам сам!",
    "Вселенная приподняла бровь.",
    "Даже робот сказал \"вау\".",
    "Удача поставила вам лайк!",
    "Картошка решила вас похвалить.",
    "Где-то плачет один математик.",
    "Это одобрено собаками!",
    "Ура! Теперь можно пить чай.",
    "Ворон крикнул \"победа!\".",
    "НЛО заинтересовалось вами.",
    "Кто-то крикнул \"ура!\" с балкона.",
    "Стул радостно заскрипел.",
    "Профессор теории в шоке.",
    "Цыплёнок доволен успехом.",
    "Ваша ставка спасла пингвина!",
    "Судьба говорит: \"Бери!\".",
    "Вы взломали код удачи!",
    "Брокколи выбрало вас героем.",
    "Вселенная вам подмигнула.",
    "Гравитация кивнула в ответ.",
    "Вам вручили невидимый приз!",
    "Вы — шаман ставок!",
    "Кто-то вздохнул с облегчением.",
    "Даже чайник рад за вас!",
    "Самурай одобрил ваш выбор.",
    "На стене появилась надпись.",
    "Лампа мигнула от восторга.",
    "Судьба подала вам знак.",
    "Где-то радуга стала ярче.",
    "Даже комар вас не укусил!",
    "Ваш холодильник доволен.",
    "Кто-то подпрыгнул от радости!",
    "Это не шутка – вы победили!",
    "Вам пришло сообщение: \"Круто!\"",
    "Гусь посмотрел на вас с уважением.",
    "Календарь сказал: \"Удача!\"",
    "Даже интернет не подвёл!",
    "Вас зауважали пельмени.",
    "Часы мигнули дважды – знак!",
    "Вы раскрыли секрет бытия!",
    "Где-то заиграла победная музыка.",
    "Кто-то мысленно вас похвалил.",
    "Дерево наклонилось к вам.",
    "Вас знают в клубе везунчиков!",
    "Кто-то крикнул: \"ВОТ ЭТО ДА!\"",
    "Облака приняли вашу ставку.",
    "Теперь вы мастер удачи.",
    "Даже рыба удивилась!",
    "Ваш успех внесён в хроники.",
    "Это зафиксировали спутники.",
    "Курица вам подмигнула.",
    "Дверь открылась сама – знак.",
    "Электронные часы показали 7:77.",
    "Вас вписали в анналы истории.",
    "Лёд в стакане зазвенел.",
    "Где-то вздохнул аналитик.",
    "Тень позади одобрила.",
    "Кто-то забил гол невидимым мячом.",
    "Угол стола стал не таким острым.",
    "Хрустнула победная печенька.",
    "Где-то хлопнули пробки шампанского.",
    "Будильник стал добрее.",
    "Под окном раздались фанфары.",
    "Ваши ботинки стали дороже.",
    "Дождь пошёл только для других.",
    "Карандаш сам наточился!",
    "Где-то перевернулся жетон.",
    "Вы — ходячий триумф!",
    "Ваша ставка вошла в учебники.",
    "Загудел радостный трамвай.",
    "Кто-то сдал экзамен случайно.",
    "Кнопка лифта нажалась сама.",
    "Даже муравьи порадовались.",
    "В словаре ваше имя — синоним удачи!",
    "Где-то открылось место в рекордах.",
    "Телефон зарядился на 1% просто так.",
    "Волосы легли идеально!",
    "В этот момент кто-то сдал экзамен.",
    "Сейф с деньгами чуть приоткрылся.",
    "Ложка не упала в тарелку!",
    "Даже подушка стала мягче.",
    "Кнопка включения загорелась раньше.",
    "Кто-то вдруг поверил в удачу.",
    "Деньги в кошельке чуть приумножились.",
    "Кто-то случайно нашёл 500 рублей.",
    "Вам выпал бесплатный кофе!",
    "Коты вашего района вас зауважали.",
    "Тапочки оказались на месте!",
    "Книга открылась на нужной странице.",
    "Вода в чайнике закипела быстрее.",
    "Лампочка загорелась чуть ярче.",
    "Где-то открылся портал удачи.",
    "Кто-то случайно нажал \"Все деньги\".",
    "Бабушка на лавочке вас оценила.",
    "Вы — официальный мастер удачи!",
    "Судьба разослала вам аплодисменты.",
    "На экране появилось \"ВЫ СУПЕР!\"",
    // [JN] Добавим абсурда!
    "Тумба-пумба!",
    "Менно-заменно.",
    "По-о-о-о-о!",
    "Ца-а!",
    "Узю!",
    "Э-эх!",
    "О-ох!",
    "Пристойно.",
    "Благочинно.",
    "Д!",
    "Быр-быр-быр!",
    "Дзаыца!!",
    "Господи, помилуй!",
    "Монетки зазвенели!",
    "Ача-ача!",
    "Ааа-ээээ!",
    "Огурчики!",
    "Помидорчики!",
    "Бонус на карту лояльности!",
    "Как в пятничку!",
    "Приходите ещё!",
    "Надо-надо!",
    "Хььььк!",
    "Ра-та-та-та!",
    "А, ооо-оо-оо!",
    // [ND]
    "Роццю!",
    "Мдао!",
    "Дяссь!",
    "Гкуньа!",
    "Зао-жунь!",
};

static const char *txt_game_loose_quotes_rus[] = {
    // [PN] Проигрышные фразы:
    "Блины подгорели.",
    "Ну, почти!",
    "Кошка на вас обиделась.",
    "Чуть-чуть не хватило!",
    "Вы всё ещё красивы!",
    "Кролик разочарован.",
    "Процессор перегрелся.",
    "Ваши очки упали.",
    "Сосед грустно посмотрел.",
    "Упс! Оп-оп!",
    "Это было немыслимо!",
    "Вы — мой герой! Но нет.",
    "Грустный звук тромбона.",
    "Обманули!",
    "Почти! (но нет).",
    "Ковёр недоволен.",
    "Кто-то вздохнул в углу.",
    "Оладушек сбежал.",
    "Это был эксперимент!",
    "Всё пошло не по плану!",
    "Велосипед молча уехал.",
    "Теперь ещё разок!",
    "Курица сказала \"нет\".",
    "Система не справилась.",
    "Банан отменён!",
    "Чайник выдал вздох разочарования.",
    "Кот ушёл в другую комнату.",
    "Судьба сделала вид, что её нет.",
    "Кто-то шепнул: \"Эх, не повезло!\"",
    "Клавиатура вздохнула вместе с вами.",
    "Вилка соскользнула со стола.",
    "Лампочка моргнула в знак печали.",
    "Стул скрипнул недовольно.",
    "Пельмень потонул в кастрюле.",
    "Телевизор включился на рекламу.",
    "Радио заиграло грустный романс.",
    "Книга закрылась сама собой.",
    "Календарь показал понедельник.",
    "Сахар не растворился в чае.",
    "Бумажка с прогнозом выпала.",
    "Очки соскользнули с носа.",
    "Ручка перестала писать.",
    "Котлетка сгорела на сковородке.",
    "Лифт уехал без вас.",
    "Кто-то где-то закрыл форточку.",
    "Колесо судьбы лопнуло.",
    "Лягушка квакнула в унисон с вами.",
    "Где-то заплакал гусь.",
    "Судьба отправила вам мем.",
    "Ветер унес надежду.",
    "Ложка упала в суп.",
    "Где-то загрустил робот.",
    "Часы отстали на пять минут.",
    "Небо сдвинуло облако не в ту сторону.",
    "Ботинки стали чуть теснее.",
    "Шнурки вдруг развязались.",
    "Кнопка лифта сломалась.",
    "Монетка упала на ребро.",
    "Шариковая ручка закончилась.",
    "Кот лениво отвернулся.",
    "Дверь хлопнула с подозрением.",
    "Огонёк свечи затрещал.",
    "Непонятный сквозняк прошёл по комнате.",
    "Вилка упала на пол.",
    "Курица снова сказала \"нет\".",
    "Батарейки разрядились в пульте.",
    "Окно браузера закрылось само.",
    "Мышка подвисла на секунду.",
    "Электричество моргнуло.",
    "Гроза началась внезапно.",
    "Книга открылась на грустной странице.",
    "Наушники запутались.",
    "Кофе остыл слишком быстро.",
    "Клавиатура зажевала кнопку.",
    "Пульт телевизора потерялся.",
    "Телефон сел в самый неподходящий момент.",
    "Обои отклеились на миллиметр.",
    "Кусочек шоколадки упал на пол.",
    "Гугл выдал не тот ответ.",
    "В дверь постучался неизвестный.",
    "Лампочка перегорела.",
    "Бумажка с важной заметкой потерялась.",
    "Зонтик сломался под дождём.",
    "В кармане оказалась дырка.",
    "Окно случайно захлопнулось.",
    "Чай оказался слишком крепким.",
    "Пара носков не сошлась.",
    "Лестница оказалась длиннее.",
    "Стул вдруг зашатался.",
    "Кофе пролился на бумагу.",
    "Кто-то кашлянул с укором.",
    "Дверь в метро закрылась перед носом.",
    "Курица вновь сказала \"нет\".",
    "Дата в календаре сменилась внезапно.",
    "Ухо зачесалось в неудобный момент.",
    "Нога запуталась в одеяле.",
    "Печь отказалась разогреваться.",
    "Где-то закрылся сундук с сокровищами.",
    "Кнопка эскалатора не сработала.",
    "Огонь в камине вдруг потух.",
    "Трава не зазеленела.",
    "Карта памяти пропала из вида.",
    "Монитор показал серый экран.",
    "Чайник вскипел слишком рано.",
    "Занавеска сдвинулась сама по себе.",
    "Облако закрыло солнце.",
    "Куртка оказалась без капюшона.",
    "Лист бумаги улетел со стола.",
    "Мост неожиданно стал разводным.",
    "Кто-то чихнул в другой комнате.",
    "Дверь в магазин закрылась перед вами.",
    "Окно троллейбуса запотело.",
    "Лампочка стала мигать.",
    "Вода в бутылке нагрелась.",
    "Капля дождя упала на лоб.",
    "В ухе зачесалось неожиданно.",
    "Вилка оказалась кривой.",
    "Часы начали тикать громче.",
    "Бумажный самолётик не полетел.",
    "Огонёк зажигалки потух.",
    "Батарейки оказались не тем размером.",
    "Программу закрыли без сохранения.",
    "Банка не открылась с первого раза.",
    "Зефир в какао утонул.",
    "Монетка упала не на ту сторону.",
    // [JN] Добавим абсурда!
    "Не надо!",
    "Ничего не надо.",
    "Пээээ!",
    "Нет.",
    "Ни.",
    "Растратно!",
    "ПЭЭЭэээ!",
    "Плохо куплено.",
    "Недостатошно.",
    "Пцьк!",
    "Досвидание.",
    "Приходите ещё!",
    "Не сказали!",
    "ТРРррщ!",
    "Псё!",
    "Кцло-о!",
    "Пцлэ-э!",
    "Пыыыы!",
    "Разорение!",
    "Крыша едет, водичка потекла.",
    "Неудовлетворительно.",
    "ПУ-УП!",
    "П-ф-ф-ф-ф...",
    "Кепочка на бок упала.",
    "Конокрадство!",
    // [ND]
    "Трыщ.",
    "Жжыц.", 
    "Сёмщ.",
    "Луфьр.",
    "Мрякс.",
};

//
// Game over
//
const char *lang_over_game;
const char *lang_over_rounds;
const char *lang_over_max_score;
const char *lang_over_enter;


// -----------------------------------------------------------------------------
// L_SetLanguageStrings
//  Инициализация и переинициализация текстовых строчек.
// -----------------------------------------------------------------------------

void L_SetLanguageStrings (void)
{
    switch (language)
    {
        case 0:  // English
            SDL_SetWindowTitle(window, "Loto Keno!");
            lang_title_name          = "Loto Keno!";
            lang_title_version       = "Version 1.0 (03/18/2025)"; // MM/DD/YYYY
            lang_title_developed_by  = "Developed and designed by:";
            lang_title_authors       = "Polina \"Aura\" N. ♥ Julia Nechaevskaya";
            lang_title_key_f1        = "F1 - Help     F2 - Language";
            lang_title_key_f2        = "F3 - Palette  F4 - Nothing!";
            lang_title_press_any_key = "Press any key...";
            lang_title_quote = txt_title_quotes_eng;
            lang_title_quote_size = sizeof(txt_title_quotes_eng) / sizeof(txt_title_quotes_eng[0]);
            
            lang_help_lines = txt_help_lines_eng;
            lang_help_lines_count = sizeof(txt_help_lines_eng) / sizeof(txt_help_lines_eng[0]);

            lang_game_score       = "      Score:";
            lang_game_bet         = "        Bet:";
            lang_game_round       = "      Round:";
            lang_game_bud_bud_bud = "Blub-blub-blub!";
            lang_game_aaa_ooo_ooo = "A-OOOO-OOO-Oo!";
            lang_game_hna         = "HNA!";
            lang_game_win_quote = txt_game_win_quotes_eng;
            lang_game_quote_win_size = sizeof(txt_game_win_quotes_eng) / sizeof(txt_game_win_quotes_eng[0]);
            lang_game_loose_quote = txt_game_loose_quotes_eng;
            lang_game_quote_loose_size = sizeof(txt_game_loose_quotes_eng) / sizeof(txt_game_loose_quotes_eng[0]);

            lang_over_game      = "GAME OVER";
            lang_over_rounds    = "       Rounds played:";
            lang_over_max_score = "         Highest win:";
            lang_over_enter     = "Press ENTER to restart";
            break;

        case 1:  // Русский
            SDL_SetWindowTitle(window, "Лото Кено!");
            lang_title_name          = "Лото Кено!";
            lang_title_version       = "Версия 1.0 (18.03.2025)"; // DD.MM.YYYY
            lang_title_developed_by  = "Разработка и идея:";
            lang_title_authors       = "Полина \"Аура\" Н. ♥ Юлия Нечаевская";
            lang_title_key_f1        = "F1 - Помощь   F2 - Язык";
            lang_title_key_f2        = "F3 - Палитра  F4 - Пусто!";
            lang_title_press_any_key = "Нажмите любую клавишу...";
            lang_title_quote = txt_title_quotes_rus;
            lang_title_quote_size = sizeof(txt_title_quotes_rus) / sizeof(txt_title_quotes_rus[0]);

            lang_help_lines = txt_help_lines_rus;
            lang_help_lines_count = sizeof(txt_help_lines_rus) / sizeof(txt_help_lines_rus[0]);

            lang_game_score       = "       Очки:";
            lang_game_bet         = "     Ставка:";
            lang_game_round       = "      Раунд:";
            lang_game_bud_bud_bud = "Будь-будь-будь!";
            lang_game_aaa_ooo_ooo = "А-ОООО-ООО-Оо!";
            lang_game_hna         = "ХНА!";
            lang_game_win_quote = txt_game_win_quotes_rus;
            lang_game_quote_win_size = sizeof(txt_game_win_quotes_rus) / sizeof(txt_game_win_quotes_rus[0]);
            lang_game_loose_quote = txt_game_loose_quotes_rus;
            lang_game_quote_loose_size = sizeof(txt_game_loose_quotes_rus) / sizeof(txt_game_loose_quotes_rus[0]);

            lang_over_game      = "ИГРА ЗАКОНЧЕНА";
            lang_over_rounds    = "        Сыграно раундов:";
            lang_over_max_score = "   Максимальный выигрыш:";
            lang_over_enter     = "Нажмите ENTER для перезапуска";
            break;
    }
    // [PN] Выбираем новую цитату при смене языка
    G_GetTitleQuote(0);
}
